version: "3.8"
services:
  mongo:
    env_file:
      - ./as_scraper/.env
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: MONGODB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local
